// cpbs

export type CpbsType = {
  name: string;
  value: number;
}

// cpbs1

export const CPBS1_CHECKPOINT_LEGACY_CONVERSION = {
  name: 'CHECKPOINT_LEGACY_CONVERSION',
  value: 0
};

export const CPBS1_CHECKPOINT_ROUND = {
  name: 'CHECKPOINT_ROUND',
  value: 1
};

export const CPBS1_CHECKPOINT_ROUND_SECONDARY = {
  name: 'CHECKPOINT_ROUND_SECONDARY',
  value: 2
};

export const CPBS1_CHECKPOINT_DISABLE_CATCHUP = {
  name: 'CHECKPOINT_DISABLE_CATCHUP',
  value: 3
};

export const CPBS1_UNUSED = {
  name: 'UNUSED',
  value: 4
};

export const CPBS1_CHECKPOINT_RESTRICTED_SPACE = {
  name: 'CHECKPOINT_RESTRICTED_SPACE',
  value: 5
};

export const CPBS1_CHECKPOINT_DISABLE_SLIPSTREAM = {
  name: 'CHECKPOINT_DISABLE_SLIPSTREAM',
  value: 6
};

export const CPBS1_CHECKPOINT_WATER = {
  name: 'CHECKPOINT_WATER',
  value: 7
};

export const CPBS1_CHECKPOINT_WATER_SECONDARY = {
  name: 'CHECKPOINT_WATER_SECONDARY',
  value: 8
};

export const CPBS1_CHECKPOINT_AIR = {
  name: 'CHECKPOINT_AIR',
  value: 9
};

export const CPBS1_CHECKPOINT_IGNORE_RESPAWNS = {
  name: 'CHECKPOINT_IGNORE_RESPAWNS',
  value: 10
};

export const CPBS1_CHECKPOINT_IGNORE_RESPAWNS_SECONDARY = {
  name: 'CHECKPOINT_IGNORE_RESPAWNS_SECONDARY',
  value: 11
};

export const CPBS1_CHECKPOINT_CENTRED_LOCATE = {
  name: 'CHECKPOINT_CENTRED_LOCATE',
  value: 12
};

export const CPBS1_CHECKPOINT_AIR_SECONDARY = {
  name: 'CHECKPOINT_AIR_SECONDARY',
  value: 13
};

export const CPBS1_CHECKPOINT_OVERRIDDEN = {
  name: 'CHECKPOINT_OVERRIDDEN',
  value: 14
};

export const CPBS1_CHECKPOINT_OVERRIDDEN_SECONDARY = {
  name: 'CHECKPOINT_OVERRIDDEN_SECONDARY',
  value: 15
};

export const CPBS1_CHECKPOINT_CUSTOM_RESPAWN_ROT = {
  name: 'CHECKPOINT_CUSTOM_RESPAWN_ROT',
  value: 16
};

export const CPBS1_CHECKPOINT_CUSTOM_RESPAWN_ROT_SECONDARY = {
  name: 'CHECKPOINT_CUSTOM_RESPAWN_ROT_SECONDARY',
  value: 17
};

export const CPBS1_CHECKPOINT_NON_BILLBOARD = {
  name: 'CHECKPOINT_NON_BILLBOARD',
  value: 18
};

export const CPBS1_CHECKPOINT_NON_BILLBOARD_SECONDARY = {
  name: 'CHECKPOINT_NON_BILLBOARD_SECONDARY',
  value: 19
};

export const CPBS1_CHECKPOINT_VEHICLE_SWAP_VEHOPTION_0 = {
  name: 'CHECKPOINT_VEHICLE_SWAP_VEHOPTION_0',
  value: 20
};

export const CPBS1_CHECKPOINT_VEHICLE_SWAP_VEHOPTION_1 = {
  name: 'CHECKPOINT_VEHICLE_SWAP_VEHOPTION_1',
  value: 21
};

export const CPBS1_CHECKPOINT_VEHICLE_SWAP_VEHOPTION_2 = {
  name: 'CHECKPOINT_VEHICLE_SWAP_VEHOPTION_2',
  value: 22
};

export const CPBS1_CHECKPOINT_VEHICLE_SWAP_VEHOPTION_SECONDARY_0 = {
  name: 'CHECKPOINT_VEHICLE_SWAP_VEHOPTION_SECONDARY_0',
  value: 23
};

export const CPBS1_CHECKPOINT_VEHICLE_SWAP_VEHOPTION_SECONDARY_1 = {
  name: 'CHECKPOINT_VEHICLE_SWAP_VEHOPTION_SECONDARY_1',
  value: 24
};

export const CPBS1_CHECKPOINT_VEHICLE_SWAP_VEHOPTION_SECONDARY_2 = {
  name: 'CHECKPOINT_VEHICLE_SWAP_VEHOPTION_SECONDARY_2',
  value: 25
};

export const CPBS1_CHECKPOINT_RESPAWN_OFFSET = {
  name: 'CHECKPOINT_RESPAWN_OFFSET',
  value: 26
};

export const CPBS1_CHECKPOINT_WARP = {
  name: 'CHECKPOINT_WARP',
  value: 27
};

export const CPBS1_CHECKPOINT_WARP_SECONDARY = {
  name: 'CHECKPOINT_WARP_SECONDARY',
  value: 28
};

export const CPBS1_CHECKPOINT_GIVE_HELP_TEXT_TO_SECONDARY_CHECKPOINT = {
  name: 'CHECKPOINT_GIVE_HELP_TEXT_TO_SECONDARY_CHECKPOINT',
  value: 29
};

export const CPBS1_CHECKPOINT_USE_VERTICAL_CAM = {
  name: 'CHECKPOINT_USE_VERTICAL_CAM',
  value: 30
};

export const CPBS1_CHECKPOINT_USE_VERTICAL_CAM_SECONDARY = {
  name: 'CHECKPOINT_USE_VERTICAL_CAM_SECONDARY',
  value: 31
};

export const CPBS1_TYPES: CpbsType[] = [
  CPBS1_CHECKPOINT_LEGACY_CONVERSION,
  CPBS1_CHECKPOINT_ROUND,
  CPBS1_CHECKPOINT_ROUND_SECONDARY,
  CPBS1_CHECKPOINT_DISABLE_CATCHUP,
  CPBS1_UNUSED,
  CPBS1_CHECKPOINT_RESTRICTED_SPACE,
  CPBS1_CHECKPOINT_DISABLE_SLIPSTREAM,
  CPBS1_CHECKPOINT_WATER,
  CPBS1_CHECKPOINT_WATER_SECONDARY,
  CPBS1_CHECKPOINT_AIR,
  CPBS1_CHECKPOINT_IGNORE_RESPAWNS,
  CPBS1_CHECKPOINT_IGNORE_RESPAWNS_SECONDARY,
  CPBS1_CHECKPOINT_CENTRED_LOCATE,
  CPBS1_CHECKPOINT_AIR_SECONDARY,
  CPBS1_CHECKPOINT_OVERRIDDEN,
  CPBS1_CHECKPOINT_OVERRIDDEN_SECONDARY,
  CPBS1_CHECKPOINT_CUSTOM_RESPAWN_ROT,
  CPBS1_CHECKPOINT_CUSTOM_RESPAWN_ROT_SECONDARY,
  CPBS1_CHECKPOINT_NON_BILLBOARD,
  CPBS1_CHECKPOINT_NON_BILLBOARD_SECONDARY,
  CPBS1_CHECKPOINT_VEHICLE_SWAP_VEHOPTION_0,
  CPBS1_CHECKPOINT_VEHICLE_SWAP_VEHOPTION_1,
  CPBS1_CHECKPOINT_VEHICLE_SWAP_VEHOPTION_2,
  CPBS1_CHECKPOINT_VEHICLE_SWAP_VEHOPTION_SECONDARY_0,
  CPBS1_CHECKPOINT_VEHICLE_SWAP_VEHOPTION_SECONDARY_1,
  CPBS1_CHECKPOINT_VEHICLE_SWAP_VEHOPTION_SECONDARY_2,
  CPBS1_CHECKPOINT_RESPAWN_OFFSET,
  CPBS1_CHECKPOINT_WARP,
  CPBS1_CHECKPOINT_WARP_SECONDARY,
  CPBS1_CHECKPOINT_GIVE_HELP_TEXT_TO_SECONDARY_CHECKPOINT,
  CPBS1_CHECKPOINT_USE_VERTICAL_CAM,
  CPBS1_CHECKPOINT_USE_VERTICAL_CAM_SECONDARY
];

// cpbs2

export const CPBS2_CHECKPOINT_VALID_WARP_EXIT = {
  name: 'CHECKPOINT_VALID_WARP_EXIT',
  value: 0
};

export const CPBS2_CHECKPOINT_VALID_WARP_EXIT_SECONDARY = {
  name: 'CHECKPOINT_VALID_WARP_EXIT_SECONDARY',
  value: 1
};

export const CPBS2_CHECKPOINT_DONT_USE_AIR_SCALE = {
  name: 'CHECKPOINT_DONT_USE_AIR_SCALE',
  value: 2
};

export const CPBS2_CHECKPOINT_DONT_USE_AIR_SCALE_SECONDARY = {
  name: 'CHECKPOINT_DONT_USE_AIR_SCALE_SECONDARY',
  value: 3
};

export const CPBS2_CHECKPOINT_SWAP_DRIVER_AND_PASSENGER = {
  name: 'CHECKPOINT_SWAP_DRIVER_AND_PASSENGER',
  value: 4
};

export const CPBS2_CHECKPOINT_UNDERWATER = {
  name: 'CHECKPOINT_UNDERWATER',
  value: 5
};

export const CPBS2_CHECKPOINT_UNDERWATER_SECONDARY = {
  name: 'CHECKPOINT_UNDERWATER_SECONDARY',
  value: 6
};

export const CPBS2_CHECKPOINT_VTOL_RESPAWN = {
  name: 'CHECKPOINT_VTOL_RESPAWN',
  value: 7
};

export const CPBS2_CHECKPOINT_SWAP_DRIVER_AND_PASSENGER_SECONDARY = {
  name: 'CHECKPOINT_SWAP_DRIVER_AND_PASSENGER_SECONDARY',
  value: 8
};

export const CPBS2_CHECKPOINT_IGNORE_Z_COORD_CHECK = {
  name: 'CHECKPOINT_IGNORE_Z_COORD_CHECK',
  value: 9
};

export const CPBS2_CHECKPOINT_IGNORE_Z_COORD_CHECK_SECONDARY = {
  name: 'CHECKPOINT_IGNORE_Z_COORD_CHECK_SECONDARY',
  value: 10
};

export const CPBS2_CHECKPOINT_FORCE_CHECKPOINT_RED = {
  name: 'CHECKPOINT_FORCE_CHECKPOINT_RED',
  value: 11
};

export const CPBS2_CHECKPOINT_FORCE_CHECKPOINT_RED_SECONDARY = {
  name: 'CHECKPOINT_FORCE_CHECKPOINT_RED_SECONDARY',
  value: 12
};

export const CPBS2_CHECKPOINT_RESTRICT_Z_CHECK = {
  name: 'CHECKPOINT_RESTRICT_Z_CHECK',
  value: 13
};

export const CPBS2_CHECKPOINT_RESTRICT_Z_CHECK_SECONDARY = {
  name: 'CHECKPOINT_RESTRICT_Z_CHECK_SECONDARY',
  value: 14
};

export const CPBS2_CHECKPOINT_RESTRICTED_SPACE_SECONDARY = {
  name: 'CHECKPOINT_RESTRICTED_SPACE_SECONDARY',
  value: 15
};

export const CPBS2_CHECKPOINT_USE_PIT_STOP_MARKER = {
  name: 'CHECKPOINT_USE_PIT_STOP_MARKER',
  value: 16
};

export const CPBS2_CHECKPOINT_USE_PIT_STOP_MARKER_SECONDARY = {
  name: 'CHECKPOINT_USE_PIT_STOP_MARKER_SECONDARY',
  value: 17
};

export const CPBS2_CHECKPOINT_LOWER_ICON = {
  name: 'CHECKPOINT_LOWER_ICON',
  value: 18
};

export const CPBS2_CHECKPOINT_LOWER_ICON_SECONDARY = {
  name: 'CHECKPOINT_LOWER_ICON_SECONDARY',
  value: 19
};

export const CPBS2_CHECKPOINT_SUPER_TALL = {
  name: 'CHECKPOINT_SUPER_TALL',
  value: 20
};

export const CPBS2_CHECKPOINT_SUPER_TALL_SECONDARY = {
  name: 'CHECKPOINT_SUPER_TALL_SECONDARY',
  value: 21
};

export const CPBS2_CHECKPOINT_INCREMENT_WANTED = {
  name: 'CHECKPOINT_INCREMENT_WANTED',
  value: 22
};

export const CPBS2_CHECKPOINT_INCREMENT_WANTED_SECONDARY = {
  name: 'CHECKPOINT_INCREMENT_WANTED_SECONDARY',
  value: 23
};

export const CPBS2_CHECKPOINT_LOW_ALPHA_CP_BLIP = {
  name: 'CHECKPOINT_LOW_ALPHA_CP_BLIP',
  value: 24
};

export const CPBS2_CHECKPOINT_LOW_ALPHA_CP_BLIP_SECONDARY = {
  name: 'CHECKPOINT_LOW_ALPHA_CP_BLIP_SECONDARY',
  value: 25
};

export const CPBS2_CHECKPOINT_INCREMENT_WANTED_TO_MAX = {
  name: 'CHECKPOINT_INCREMENT_WANTED_TO_MAX',
  value: 26
};

export const CPBS2_CHECKPOINT_INCREMENT_WANTED_TO_MAX_SECONDARY = {
  name: 'CHECKPOINT_INCREMENT_WANTED_TO_MAX_SECONDARY',
  value: 27
};

export const CPBS2_TYPES: CpbsType[] = [
  CPBS2_CHECKPOINT_VALID_WARP_EXIT,
  CPBS2_CHECKPOINT_VALID_WARP_EXIT_SECONDARY,
  CPBS2_CHECKPOINT_DONT_USE_AIR_SCALE,
  CPBS2_CHECKPOINT_DONT_USE_AIR_SCALE_SECONDARY,
  CPBS2_CHECKPOINT_SWAP_DRIVER_AND_PASSENGER,
  CPBS2_CHECKPOINT_UNDERWATER,
  CPBS2_CHECKPOINT_UNDERWATER_SECONDARY,
  CPBS2_CHECKPOINT_VTOL_RESPAWN,
  CPBS2_CHECKPOINT_SWAP_DRIVER_AND_PASSENGER_SECONDARY,
  CPBS2_CHECKPOINT_IGNORE_Z_COORD_CHECK,
  CPBS2_CHECKPOINT_IGNORE_Z_COORD_CHECK_SECONDARY,
  CPBS2_CHECKPOINT_FORCE_CHECKPOINT_RED,
  CPBS2_CHECKPOINT_FORCE_CHECKPOINT_RED_SECONDARY,
  CPBS2_CHECKPOINT_RESTRICT_Z_CHECK,
  CPBS2_CHECKPOINT_RESTRICT_Z_CHECK_SECONDARY,
  CPBS2_CHECKPOINT_RESTRICTED_SPACE_SECONDARY,
  CPBS2_CHECKPOINT_USE_PIT_STOP_MARKER,
  CPBS2_CHECKPOINT_USE_PIT_STOP_MARKER_SECONDARY,
  CPBS2_CHECKPOINT_LOWER_ICON,
  CPBS2_CHECKPOINT_LOWER_ICON_SECONDARY,
  CPBS2_CHECKPOINT_SUPER_TALL,
  CPBS2_CHECKPOINT_SUPER_TALL_SECONDARY,
  CPBS2_CHECKPOINT_INCREMENT_WANTED,
  CPBS2_CHECKPOINT_INCREMENT_WANTED_SECONDARY,
  CPBS2_CHECKPOINT_LOW_ALPHA_CP_BLIP,
  CPBS2_CHECKPOINT_LOW_ALPHA_CP_BLIP_SECONDARY,
  CPBS2_CHECKPOINT_INCREMENT_WANTED_TO_MAX,
  CPBS2_CHECKPOINT_INCREMENT_WANTED_TO_MAX_SECONDARY
];

/**
 * A list of unique checkpoint types (I assume).
 *
 * Taken from: <a href="https://github.com/taoletsgo/custom_races/blob/f96528d4665d83281ecfd8c93c857d19ffeefefb/main script/custom_races/server/races_room.lua">github.com/taoletsgo/custom_races</a>
 *
 * Credit to the original authors.
 */
export const CPBS_TYPES = {
  cpbs1: CPBS1_TYPES,
  cpbs2: CPBS2_TYPES
};
